# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71afa4e8c2f146e726b1c6a151a999257f36abedc1c294d41594cb8665b6d612c242fcf154c074d7e96d1222c376954e6ffc8087e2a7caefef638c3fec9e8471

test:
  secret_key_base: 2f444865a3174d1c714b4fa79a3792ec7cecbc97ea7814cf6f12d1172466643dd2679d400132a2e905c1ad057ecdb5699c745b5e1b34f3439080c7c3b8697a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
